# Generated by Django 4.2.2 on 2023-07-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('S_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=500)),
                ('timestemp', models.DateField(blank=True)),
            ],
        ),
    ]
